export interface IWorkOrder {
  // Generated by https://quicktype.io

  ot_number?: number;
  date: null;
  observations: string;
  is_confirmed: boolean;
  is_payment: boolean;
  createdAt?: string;
  updatedAt?: string;
  license_vehicle?: string;
  ot_type?: number;
  spares_stock?:string;
  
}
